// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(StudyPalDbContext))]
    partial class StudyPalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("API.Models.StudyArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StudyAreas");
                });

            modelBuilder.Entity("API.Models.StudyGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("CompletedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StudyAreaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("StudyAreaId");

                    b.ToTable("StudyGoals");
                });

            modelBuilder.Entity("API.Models.StudySession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FollowUpQuestions")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FollowUpResponses")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LearningNote")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StudiedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudyGoalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudyGoalId");

                    b.ToTable("StudySessions", t =>
                        {
                            t.HasCheckConstraint("CK_StudySessions_DurationMinutes_Positive", "DurationMinutes > 0");
                        });
                });

            modelBuilder.Entity("API.Models.StudyTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudyGoalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudyGoalId", "Type")
                        .IsUnique();

                    b.ToTable("StudyTargets", t =>
                        {
                            t.HasCheckConstraint("CK_StudyTargets_Value_Positive", "Value > 0");
                        });
                });

            modelBuilder.Entity("API.Models.StudyGoal", b =>
                {
                    b.HasOne("API.Models.StudyArea", "StudyArea")
                        .WithMany("StudyGoals")
                        .HasForeignKey("StudyAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("StudyArea");
                });

            modelBuilder.Entity("API.Models.StudySession", b =>
                {
                    b.HasOne("API.Models.StudyGoal", "StudyGoal")
                        .WithMany("StudySessions")
                        .HasForeignKey("StudyGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyGoal");
                });

            modelBuilder.Entity("API.Models.StudyTarget", b =>
                {
                    b.HasOne("API.Models.StudyGoal", "StudyGoal")
                        .WithMany("StudyTargets")
                        .HasForeignKey("StudyGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyGoal");
                });

            modelBuilder.Entity("API.Models.StudyArea", b =>
                {
                    b.Navigation("StudyGoals");
                });

            modelBuilder.Entity("API.Models.StudyGoal", b =>
                {
                    b.Navigation("StudySessions");

                    b.Navigation("StudyTargets");
                });
#pragma warning restore 612, 618
        }
    }
}
