/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyAreasRouteImport } from './routes/study-areas'
import { Route as IndexRouteImport } from './routes/index'

const StudyAreasRoute = StudyAreasRouteImport.update({
  id: '/study-areas',
  path: '/study-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/study-areas': typeof StudyAreasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/study-areas': typeof StudyAreasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/study-areas': typeof StudyAreasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/study-areas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/study-areas'
  id: '__root__' | '/' | '/study-areas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudyAreasRoute: typeof StudyAreasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study-areas': {
      id: '/study-areas'
      path: '/study-areas'
      fullPath: '/study-areas'
      preLoaderRoute: typeof StudyAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudyAreasRoute: StudyAreasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
